title: Zeyad Ghoneim
#logo: Assets/img/photo_6012759261995713449_y.jpg"
description: Passion-driven security specialist thriving in collaborative enviroments trying to stay forefront of the ever-evolving Cybersecurity landscape.
#show downloads: true
theme: jekyll-theme-minimal 
